server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      
spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://localhost:3306/greendb
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234
      
mustache:
  expose-session-attributes: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # entity를 만들때 변수명 그대로 디비에 필드를 넣어줌
    show-sql: true # 콘솔창에 생성된 테이블 보여줌
    properties:
      hibernate.format_sql: true # 콘솔 이쁘게 정렬

  output:
    ansi:
      enabled: always


